# Generated by Django 4.0.1 on 2022-01-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя артиста')),
                ('descr', models.CharField(max_length=200, verbose_name='Описание артиста')),
                ('avatar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена билета')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес проведения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('descr', models.CharField(max_length=200, verbose_name='Описание мероприятия')),
                ('age_rating', models.CharField(max_length=5, verbose_name='Возрастной рейтинг')),
                ('pic', models.CharField(max_length=200)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.artist', verbose_name='Имя артиста')),
            ],
        ),
    ]
