# Generated by Django 4.0.1 on 2022-01-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
